CREATE TABLE analysis_result (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 file_name VARCHAR(255) NOT NULL,
                                 file_size_bytes BIGINT NOT NULL,
                                 temp_file_path VARCHAR(500),
                                 uploaded_at TIMESTAMP NOT NULL,
                                 processed_at TIMESTAMP,
                                 process_duration_millis BIGINT,
                                 metrics TEXT,
                                 status VARCHAR(50) NOT NULL
);