CREATE TABLE analysis_record (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 file_name VARCHAR(255) NOT NULL,
                                 file_size_bytes BIGINT NOT NULL,
                                 temp_file_path VARCHAR(500),
                                 uploaded_at TIMESTAMP NOT NULL,
                                 processed_at TIMESTAMP,
                                 process_duration_millis BIGINT,
                                 count BIGINT,
                                 min_value DOUBLE PRECISION,
                                 max_value DOUBLE PRECISION,
                                 avg DOUBLE PRECISION,
                                 std_dev DOUBLE PRECISION,
                                 skip_count BIGINT,
                                 unique_count BIGINT,
                                 status VARCHAR(50) NOT NULL
);